language: c
script: make gcov && make test-valgrind
after_success:
    - coveralls --exclude test
compiler:
    - gcc
    - clang
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - valgrind
            - lcov
before_install:
    - pip install --user urllib3[secure]
    - pip install --user cpp-coveralls
sudo: false
