language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.6
            - lcov
      env: COMPILER=gcc-4.6 COVERALL_OPTS='--gcov gcov-4.6' TARGET=test
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - lcov
      env: COMPILER=gcc-4.9 COVERALL_OPTS='--gcov gcov-4.9' TARGET=test
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - lcov
      env: COMPILER=gcc-5 COVERALL_OPTS='--gcov gcov-5' TARGET=test
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - lcov
      env: COMPILER=gcc-6 COVERALL_OPTS='--gcov gcov-6' TARGET=test
    - os: linux
      compiler: clang
      env: COMPILER=clang COVERALL_OPTS='' TARGET=test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lcov
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - valgrind
            - lcov
      env: COMPILER=gcc-4.9 COVERALL_OPTS='--gcov gcov-4.9' TARGET=test-valgrind
    - os: linux
      compiler: clang
      env: COMPILER=clang COVERALL_OPTS='' TARGET=test-valgrind
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lcov
            - valgrind
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env: COMPILER=gcc-4.9 TARGET=bench



script: CC=$COMPILER make gcov && CC=$COMPILER make $TARGET
after_success:
    - test $TARGET = "test" && coveralls $COVERALL_OPTS -i src
before_install:
    - pip install --user urllib3[secure]
    - pip install --user cpp-coveralls
sudo: false
